### ISSUE TITLE
RP2040 support (tested?)

### ISSUE THREAD

**Issue by bradanlane** [marcel-licence/ml_synth_basic_example#2]
I am guessing it's difficult if not impossible to test all the hardware variations. I am seeing an error when using the RP2040 _(eg Raspberry Pi PICO)_.

For all instances of `Serial.printf()` The compiler is reporting `error: 'class arduino::UART' has no member named 'printf'`.

This does not appear to be an issue with ESP32 boards.

Disregard. It's a compiler configuration mistake.

**Comment by marcel-licence** [comment]
Please refer to https://github.com/marcel-licence/ml_synth_basic_example/blob/main/doc/board_info.md
I guess you didn't use the Adafruit Tiny USB. I've listed all tested compilations

**Comment by bradanlane** [comment]
The problem appears to be the new Arduino IDE2 has changed the version of the tool chain for RP2040 to the 4.0.2 mbed version which does not have `printf` for rp2040.

**Comment by marcel-licence** [comment]
Hm, I think it should work. Did you went through the guide? https://www.youtube.com/watch?v=Cu8vTbmy_Ao
I didn't use the Mbed OS RP2040 Boards. I used "Raspberry Pi Pico/RP2040" instead. It is also listed in the board_info.md. I could add some links in future to make it easier to identify which board was used for compilation.

**Comment by bradanlane** [comment]
all good now. testing stuff
