### ISSUE TITLE
Enhancment: Use Second Core on RP2040

### ISSUE THREAD

**Issue by bradanlane** [marcel-licence/ml_synth_basic_example#3]
The RP2040 uses the Arduino_Pico environment which provides easy support for running code on the second core.

The standard Arduino functions `setup()` and `loop()` run on the first core. The second core runs `setup1()` and `loop1()`.

As a test, I moved the LED blink 1hz to the second core and used the data communications provided by `rp2040.fifi.push_nb()`, `rp2040.fifi.pop_nb()`, and `rp2040.fifi.available()` to signal the second core when the first core was finished with its initialization.

More details are available here: https://arduino-pico.readthedocs.io/en/latest/multicore.html

_(this enhancement would be applicable to all of the projects built for the RP2040)_

**Comment by marcel-licence** [comment]
It is intentional that I try to use only one core for all time critical tasks to leave the second core free for other users to use for all other tasks.
The ESP32 code works similar. For example the display is driven by the second core. Thank you very much for your input

**Comment by bradanlane** [comment]
That makes sense. I was thinking the second core would be used for non-time-critical tasks, similar to the ESP32.

_I only used the LED as my test to verify the design actually worked._

**Comment by marcel-licence** [comment]
I made also tests with a display which cannot be updated within the audio loop without any audible noise.
Using loop1() does work.
I may be possible that using different libraries will create different results.
Can this issue be closed?

**Comment by bradanlane** [comment]
This can be closed. I will keep it in mind for future work. 

Based on my initial investigations, I will likely switch from the RP2040 to an ESP32-S3 for my hardware design.

**Comment by marcel-licence** [comment]
Did you find a way to run the internal DAC with DMA on the S3? I wanted to get it running on the S2 but seems the IDF is still under development.

**Comment by bradanlane** [comment]
I will plan to use I2S and an external module (similar to your prior projects). I have not yet chosen the external chip.

**Comment by marcel-licence** [comment]
Usually I prefer using an external codec too. This experiment using PWM should give anyone a chance to get sound their setup with less effort
